# Generated by Django 2.1.2 on 2018-10-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fire',
            unique_together={('lat', 'lng')},
        ),
    ]
